### PR TITLE
fixed check in endpoint and added error for duplicate check in

### LINKED ISSUE #67: Self checkin returns 400

### PR DESCRIPTION
**Pull request by anudaweerasinghe**
Resolves #67 and adds duplicate check in check

### CODE REVIEW

File: src/controllers/CheckInController.ts [hunk 1]
```diff
@@ -213,14 +213,24 @@ export const checkInUser = async (
...
+
+    const data = {
       user: user._id,
       item: item._id,
-      event: event,
-    });
+      event: event._id,
+    };
+
+    //check if user has already been checked in
```
Comment (anudaweerasinghe) [inline src/controllers/CheckInController.ts:227]: @gramliu do you think this should be moved to the canCheckIn middleware function?

Comment (gramliu) [reply src/controllers/CheckInController.ts:227]: Yeah, I think it might be better to move it to the middleware
